name: Test

on: [push]

env: # environment variables (available in any part of the action)
  NODE_VERSION: 16

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Code Testing
        run: npm run test